apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs1
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /os4
    server: 192.168.99.253 
  persistentVolumeReclaimPolicy: Retain 
