apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-registry-pvc 
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-nfs1
  storageClassName: ""
